# Generated by Django 4.1.3 on 2022-12-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mode_of_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='question_categories',
        ),
    ]
